### ISSUE TITLE
ic_launcher.png 是一个jpeg文件，不是PNG

### ISSUE THREAD

**Issue by Jamol** [bmob/bmob-android-im-sdk#1]
ic_launcher.png 是一个jpeg文件，转成AS工程时后编译不过。

**Comment by cvvbbo** [comment]
这个问题遇到过。。我是这样解决的把原生的ic_launcher.png代替原来的ic_launcher.png就可以了
我想问楼主，他这个注册写的不全啊，貌似没有判断账号重复了的情况啊~

**Comment by Jamol** [comment]
是的 他这个只是最基本功能的一个demo，很多错误处理都没做

**Comment by 307572384** [comment]
换成jpg就行了
